#!/data/data/com.termux/files/usr/bin/bash -e 
#
#
#	Script programmed by me [ RaulXH ]
#
#
#
#	Script original
#
#
#[ Credits to my freind github.com/Abhackeroficcial ] 
#
#
# 
# 	This is not anyone's copy. 
#
#
# 	[ RaulXH ] [ Panamá ]
#
# Colores 
AGUA="\e[2;50;36m" 
RED="\e[0;50;91m"            
GREEN="\e[0;50;32m"   
YELOW="\e[0;50;33m"
XH='\e[7;107;31m'
FORT="\e[0m"
ARCH=$(dpkg --print-architecture)
#
[[ ! -f $(type -P wget2) ]] && printf "[ wget2 not installed ]" && exit 1
function installruby()
{	printf "${XH}[ Downloading ruby for Termux ]$FORT\n\n"
	case $ARCH in
		arm|aarch64|i686)
			wget2 --progress=bar --tries=20 https://github.com/RaulXH/Packages-for-termux/blob/main/ruby_2.7.2-${ARCH}.deb?raw=true -O "ruby_2.7.2-${ARCH}.deb"
		apt install "./ruby_2.7.2-${ARCH}.deb" -y
		rm -rf ruby_2*
		;;
	*)
		printf "\n${RED}[ Architecture not found ] ${FORT}\n"
		exit 1
		;;
	esac


}
if  [[  -f $PREFIX/bin/ruby ]]
then
	#
	VERSION=$(ruby --version | awk '{print $2}')
	if [[ ${VERSION%.*} =~ "2.7" ]]
	then
		echo -e "\n${GREEN}[*] ${WHITE}Ruby Installed with version ${RED}2.7.2! ${GREEN}[*]${FORT}\n"
	else
		echo -e "\n${GREEN}[*] ${WHITE}Ruby Installed with version ${RED}${VERSION}! ${GREEN}[*]${FORT}\n"
		echo -e "\n${RED}[!] ${AGUA}Uninstalling ruby ${VERSION} ${RED}[!]${FORT}\n"
		apt purge ruby -y &>/dev/null
		sleep 3
		installruby
		
	fi
else
	sleep 2
	installruby
fi
#
#
#
#
#
#
#	
#
#
#
#
#
#		[ Creado por RaulXH ]
#
#
#
#
#
#
#
#		[ Panamá ]
#
