#!/data/data/com.termux/files/usr/bin/bash -e 
#
#
#	Script programmed by me [ RaulXH ]
#
#
#
#	Script original
#
#
#	[ Credits to my freind Abhackeroficcial ] 
#
#
# 
# 	This is not anyone's copy. 
#
#
# 	[ RaulXH ] [ Panamá ]
#
# Colores 
AGUA="\e[2;50;36m" 
RED="\e[0;50;91m"            
GREEN="\e[0;50;32m"   
YELOW="\e[0;50;33m"
XH='\e[7;107;31m'
FORT="\e[0m"
HF=$(dpkg --print-architecture)
#
function installruby()
{	printf "${XH}[ Downloading ruby for Termux ]$FORT\n\n"
	if [[ $HF = 'arm' ]]
	then
		wget2 --progress=bar --tries=20 https://github.com/RaulXH/Ruby-for-Termux/blob/main/ruby_2.7.2-arm.deb?raw=true -O 'ruby ruby_2.7.2-arm.deb'
		apt install ./ruby_2.7.2-arm.deb -y
		rm -rf ruby_2*
		#DONE
	elif [[ $HF = 'aarch64' ]]
	then
		wget2 --progress=bar --tries=20 https://github.com/RaulXH/Ruby-for-Termux/blob/main/ruby_2.7.2-aarch64.deb?raw=true -O 'ruby_2.7.2-aarch64.deb'
		apt install ./ruby_2.7.2-aarch64.deb -y
		rm -rf ruby_2*
		#DONE
	else
		printf "\nArchitecture no found :(\n"
		exit 0
	fi

}
if  [[  -f $PREFIX/bin/ruby ]]
then
	#
	# Si ruby existe y no esta la version 2.7.2
	#
	VERSION=$(ruby --version | awk '{print $2}')
	if [[ ${VERSION%.*} =~ "2.7" ]]
	then
		echo -e "\n${GREEN}[*] ${WHITE}Ruby Installed with version ${RED}2.7.2! ${GREEN}[*]${FORT}\n"
	else
		echo -e "\n${GREEN}[*] ${WHITE}Ruby Installed with version ${RED}${VERSION}! ${GREEN}[*]${FORT}\n"
		echo -e "\n${RED}[!] ${AGUA}Uninstalling ruby ${VERSION} ${RED}[!]${FORT}\n"
		apt purge ruby -y &>/dev/null
		sleep 3
		installruby
		
	fi
else
	#
	# Ruby no existe e Instala
	#
	sleep 2
	installruby
fi
#
#
#
#
#
#
#	
#
#
#
#
#
#		[ Creado por RaulXH ]
#
#
#
#
#
#
#
#		[ Panamá ]
#
