#!/data/data/com.termux/files/usr/bin/bash -e
#
#
#
URL='https://github.com/rapid7/metasploit-framework/releases'
[[ ! $(type -P wget2) ]] && printf "\n[ Wget2 not installed ]\n\n" && exit 1
[[ ! -f 'MSFinstaller' ]] && printf "\n[ MSFinstallee not found! ]\n\n" && exit 1
VERSION=''
NEW=$(w3m -dump https://github.com/rapid7/metasploit-framework/releases | grep -A3 -i 'release' | tail -n1)
OLD=$(sed -n '/^MSFVERSION/p' MSFinstaller | awk -F= '{print $2}')
#
# Url metasploit release Update
#
URL="https://github.com/rapid7/metasploit-framework/archive/refs/tags/${NEW}.tar.gz"
#
if [[ $NEW != $OLD ]]
then
	HASHOLD=$(sed -n '/TERMUX\_MD5SUM\_MSF\=/p' MSFinstaller | awk -F= '{print $2}')
	printf "\n[ Update Metasploit Version: \e[1;50;36m$NEW\e[0m ]\n\n"
	printf "| \e[7;50;94mDownloading Release Metasploit\e[0m |\n"
	wget2 --progress=bar --tries=20 $URL
	#
	printf "\n[ \e[7;50;94mMd5sum for package\e[0m ]\n\n"
	MD5SUM="$(md5sum ${NEW}.tar.gz | awk '{print $1}')"
	sed -i "s/$OLD/$NEW/" MSFinstaller
	# Hash
	sed -i "s/$HASHOLD/$MD5SUM/" MSFinstaller
	sleep 3
	rm -rf "${NEW}.tar.gz"
	printf "[ \e[1;50;32mDone!\e[0m ]\n\n"
else
	printf "\n\e[0;100;94m[+ Update Metasploit Package +]\e[0m\n\n"
	exit 0
fi


